requireLogin();(function(){
  const filtroInicio=document.getElementById('filtroInicio'); const filtroFim=document.getElementById('filtroFim'); const btnFiltrar=document.getElementById('btnFiltrar'); const tabela=document.getElementById('tabelaHistorico').querySelector('tbody'); const resumo=document.getElementById('resumoHistorico'); const graficoBarra=document.getElementById('graficoBarra'); const graficoEsforco=document.getElementById('graficoEsforco'); const graficoConclusao=document.getElementById('graficoConclusao'); const btnExportarPDF=document.getElementById('btnExportarPDF'); const btnExportarCSV=document.getElementById('btnExportarCSV');
  function render(){ const store=loadStore(); const todas=Object.keys(store).sort(); const inicio=filtroInicio.value?filtroInicio.value:null; const fim=filtroFim.value?filtroFim.value:null; const filtradas=todas.filter(d=>{ if(inicio && d<inicio) return false; if(fim && d>fim) return false; return true; }); tabela.innerHTML=''; let totPrev=0, totExec=0; const dados=[]; const esforcos=[]; const conclusoes=[]; filtradas.forEach(d=>{ const s=store[d]; const res=s.resumo || {previstos:(s.exercicios||[]).length, executados:(s.exercicios||[]).filter(e=>e.done).length}; const pct=res.previstos?Math.round(100*res.executados/res.previstos):0; const esforco = s.meta?.esforco || null; totPrev+=res.previstos; totExec+=res.executados; const tr=document.createElement('tr'); tr.innerHTML=`<td>${formatBR(d)}</td><td>${res.previstos}</td><td>${res.executados}</td><td>${pct}%</td>`; tabela.appendChild(tr); dados.push({ d, prev:res.previstos, exec:res.executados, pct }); if(esforco!==null) esforcos.push({ d, val:esforco }); conclusoes.push({ d, pct }); }); const pctTot=totPrev?Math.round(100*totExec/totPrev):0; resumo.innerHTML = `<div class="row"><div class="col"><strong>Dias no período:</strong> ${filtradas.length}</div><div class="col"><strong>Previstos:</strong> ${totPrev}</div><div class="col"><strong>Executados:</strong> ${totExec}</div></div><div class="progress mt-1"><div style="width:${pctTot}%"></div></div><div class="hint">Concluído: ${pctTot}%</div>`;
    const W=graficoBarra.clientWidth||600, H=160, pad=30; const maxY=Math.max(1,...dados.map(x=>Math.max(x.prev,x.exec))); const step=(W-pad*2)/Math.max(1,dados.length); let svg=`<svg class="bar-chart" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`; svg+=`<line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" stroke="#6b7280" stroke-width="1"/>`; dados.forEach((x,i)=>{ const x0=pad+i*step+6; const hPrev=Math.round((x.prev/maxY)*(H-pad-20)); const hExec=Math.round((x.exec/maxY)*(H-pad-20)); const yPrev=(H-pad)-hPrev; const yExec=(H-pad)-hExec; svg+=`<rect x="${x0}" y="${yPrev}" width="10" height="${hPrev}" fill="#93c5fd"/>`; svg+=`<rect x="${x0+14}" y="${yExec}" width="10" height="${hExec}" fill="#22c55e"/>`; }); svg+='</svg>'; graficoBarra.innerHTML=svg;
    const W2=graficoEsforco.clientWidth||600, H2=160; const pad2=30; const step2=(W2-pad2*2)/Math.max(1,esforcos.length); let svg2=`<svg class="bar-chart" viewBox="0 0 ${W2} ${H2}" preserveAspectRatio="none">`; svg2+=`<line x1="${pad2}" y1="${H2-pad2}" x2="${W2-pad2}" y2="${H2-pad2}" stroke="#6b7280" stroke-width="1"/>`; let path=''; esforcos.forEach((x,i)=>{ const xPos=pad2+i*step2; const yPos=(H2-pad2) - Math.round(((x.val-1)/9)*(H2-pad2-20)); path += (i===0?`M ${xPos} ${yPos}`:` L ${xPos} ${yPos}`); svg2+=`<circle cx="${xPos}" cy="${yPos}" r="2" fill="#f59e0b"/>`; }); svg2+=`<path d="${path}" stroke="#f59e0b" stroke-width="2" fill="none"/>`; svg2+='</svg>'; graficoEsforco.innerHTML=svg2;
    const W3=graficoConclusao.clientWidth||600, H3=160; const pad3=30; const step3=(W3-pad3*2)/Math.max(1,conclusoes.length); let svg3=`<svg class="bar-chart" viewBox="0 0 ${W3} ${H3}" preserveAspectRatio="none">`; svg3+=`<line x1="${pad3}" y1="${H3-pad3}" x2="${W3-pad3}" y2="${H3-pad3}" stroke="#6b7280" stroke-width="1"/>`; let path3=''; conclusoes.forEach((x,i)=>{ const xPos=pad3+i*step3; const yPos=(H3-pad3) - Math.round(((x.pct)/100)*(H3-pad3-20)); path3 += (i===0?`M ${xPos} ${yPos}`:` L ${xPos} ${yPos}`); svg3+=`<circle cx="${xPos}" cy="${yPos}" r="2" fill="#3b82f6"/>`; }); svg3+=`<path d="${path3}" stroke="#3b82f6" stroke-width="2" fill="none"/>`; svg3+='</svg>'; graficoConclusao.innerHTML=svg3;
    const q=new URLSearchParams(); if(inicio) q.set('inicio',inicio); if(fim) q.set('fim',fim); btnExportarPDF.href='relatorio.html?'+q.toString();
    btnExportarCSV.onclick = ()=>{ let csv = 'Data,Previstos,Executados,Conclusao(%)\n'; dados.forEach(x=>{ csv += `${formatBR(x.d)},${x.prev},${x.exec},${x.pct}\n`; }); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='historico_'+currentProfile()+'.csv'; a.click(); URL.revokeObjectURL(url); };
  }
  btnFiltrar.addEventListener('click', render); render();
})();
