requireLogin();(function(){
  const params=new URLSearchParams(window.location.search); const iso=params.get('date'); if(!iso){ window.location.href='calendar.html'; return; }
  const titulo=document.getElementById('treinoTitulo'); const lista=document.getElementById('listaExercicios'); const btnSalvar=document.getElementById('btnSalvarTreino'); const btnAdd=document.getElementById('btnAddExercicio'); const btnTodos=document.getElementById('btnTodosRealizados'); const obs=document.getElementById('obs'); const esforco=document.getElementById('esforco'); const esforcoValor=document.getElementById('esforcoValor');
  esforco.addEventListener('input',()=>{ esforcoValor.textContent=esforco.value; });
  function render(){ titulo.textContent = (I18N[(localStorage.getItem('lang')||'pt')].day_training || 'Treino do dia') + ' ' + formatBR(iso); const store=loadStore(); if(!store[iso]){ const plano=planoPorDia(iso).map((ex,idx)=>({ id:`${iso}-${idx}`, cat:ex.cat, nome:ex.nome, meta:ex.meta, video:ex.video, icon:ex.icon, done:false })); store[iso] = { exercicios:plano, meta:{obs:'',esforco:5} }; saveStore(store); }
    const exercicios=store[iso].exercicios; obs.value=(store[iso].meta?.obs)||''; esforco.value=(store[iso].meta?.esforco)||5; esforcoValor.textContent=esforco.value; lista.innerHTML=''; const porCat={}; exercicios.forEach(e=>{ porCat[e.cat]=porCat[e.cat]||[]; porCat[e.cat].push(e); }); Object.keys(porCat).forEach(cat=>{ const h=document.createElement('h3'); h.className='section-title'; h.textContent=cat; lista.appendChild(h); porCat[cat].forEach(e=>{ const div=document.createElement('div'); div.className='exercise'+(e.done?' done':''); const id=e.id; div.innerHTML=`<div class="title">${e.icon?'<img class="icon-inline" src="icons_ex/'+e.icon+'" alt="">':''}${e.nome}</div><div class="meta">Meta: ${e.meta}</div><div class="actions"><button class="btn ${e.done?'primary':''}" data-action="done">Realizado</button><button class="btn" data-action="not">Não</button><a class="btn" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent(e.video)}">Ver vídeo</a><button class="btn danger" data-action="rem">Remover</button></div>`; div.querySelector('[data-action="done"]').addEventListener('click',()=>{ e.done=true; div.classList.add('done'); }); div.querySelector('[data-action="not"]').addEventListener('click',()=>{ e.done=false; div.classList.remove('done'); }); div.querySelector('[data-action="rem"]').addEventListener('click',()=>{ const s=loadStore(); s[iso].exercicios = s[iso].exercicios.filter(x=>x.id!==id); saveStore(s); render(); }); lista.appendChild(div); }); }); }
  btnAdd.addEventListener('click',()=>{ const nome=prompt('Nome do exercício:'); if(!nome) return; const cat=prompt('Categoria (Habilidade/Arranque/Mentalidade):')||'Habilidade'; const meta=prompt('Meta (ex.: 3×30 s, 5 repetições, 2×2 min):')||''; const video=prompt('Termos para pesquisa no YouTube (opcional):')||nome; const icon=prompt('Ícone (cones.svg, ball.svg, ladder.svg, sprint.svg, brain.svg) opcional:')||''; const s=loadStore(); const list=s[iso]?.exercicios||[]; const id=iso+'-'+Math.random().toString(36).slice(2,7); list.push({id,cat,nome,meta,video,icon,done:false}); s[iso] = { exercicios:list, meta: s[iso]?.meta || {obs:'',esforco:5} }; saveStore(s); render(); });
  btnTodos.addEventListener('click',()=>{ const s=loadStore(); (s[iso]?.exercicios||[]).forEach(e=> e.done=true); saveStore(s); render(); });
  btnSalvar.addEventListener('click',()=>{ const s=loadStore(); const exercicios=s[iso]?.exercicios||[]; const previstos=exercicios.length; const executados=exercicios.filter(e=>e.done).length; s[iso] = { exercicios, resumo:{previstos,executados}, meta:{obs:obs.value,esforco:parseInt(esforco.value,10)||5} }; saveStore(s); alert('Progresso salvo!'); });
  render();
})();
